name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: pypi-publish
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test_sqlfun
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up PDM
      uses: pdm-project/setup-pdm@v3
      with:
        python-version: 3.9
        cache: true

    - name: Install dependencies
      run: pdm install -v --dev

    - name: Run tests
      run: pdm run pytest tests/

    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref }}
        tag_name: ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Build and publish to PyPI
      env:
        PDM_PUBLISH_USERNAME: ${{ secrets.PDM_PUBLISH_USERNAME }}
        PDM_PUBLISH_PASSWORD: ${{ secrets.PDM_PUBLISH_PASSWORD }}
      run: |
        pdm publish
