name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: pypi-publish
    permissions:
      # for creating github release
      contents: write
      # for trusted publishing
      id-token: write
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up PDM
      uses: pdm-project/setup-pdm@v3
      with:
        python-version: 3.9
        cache: true

    - name: Install dependencies
      run: pdm sync -v --dev

    - name: Run tests
      run: pdm run pytest tests/

    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref }}
        tag_name: ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Build and publish to PyPI
      run: |
        pdm publish
